/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * AccountCreds represents an account credentials (either, username- or token-based).
 */
export class AccountCredsRequest extends SpeakeasyBase {
    /**
     * Account credentials expiration timestamp.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "expires" })
    expires?: string;

    /**
     * Account password or token secret.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "password" })
    password: string;

    /**
     * Security account login or token.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "username" })
    username: string;
}
