/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { EnvironmentBaseRequest } from "./environmentbaserequest";
import { Expose, Type } from "class-transformer";

/**
 * The request ID, Human-friendly name and environment of the Application.
 *
 * @remarks
 *
 *
 */
export class ApplicationCreationRequest extends SpeakeasyBase {
  @SpeakeasyMetadata()
  @Expose({ name: "env" })
  @Type(() => EnvironmentBaseRequest)
  env?: EnvironmentBaseRequest;

  /**
   * The ID which refers to a specific application.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "id" })
  id: string;

  /**
   * The Human-friendly name for the Application.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "name" })
  name: string;
}
