/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { EnvironmentBaseResponse } from "./environmentbaseresponse";
import { Expose, Type } from "class-transformer";

/**
 * An Application is a collection of Workloads that work together. When deployed, all Workloads in an Application are deployed to the same namespace.
 *
 * @remarks
 *
 * Apps are the root of the configuration tree holding Environments, Deployments, Shared Values, and Secrets.
 */
export class ApplicationResponse extends SpeakeasyBase {
  /**
   * The timestamp in UTC indicates when the Application was created.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "created_at" })
  createdAt: string;

  /**
   * The user who created the Application.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "created_by" })
  createdBy: string;

  /**
   * The Environments associated with the Application.
   */
  @SpeakeasyMetadata({ elemType: EnvironmentBaseResponse })
  @Expose({ name: "envs" })
  @Type(() => EnvironmentBaseResponse)
  envs: EnvironmentBaseResponse[];

  /**
   * The ID which refers to a specific application.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "id" })
  id: string;

  /**
   * The Human-friendly name for the Application.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "name" })
  name: string;
}
