/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { PodStateResponse } from "./podstateresponse";
import { Expose, Type } from "class-transformer";

/**
 * Controller represents deployment, stateful set etc
 */
export class ControllerResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "kind" })
    kind: string;

    @SpeakeasyMetadata()
    @Expose({ name: "message" })
    message: string;

    @SpeakeasyMetadata({ elemType: PodStateResponse })
    @Expose({ name: "pods" })
    @Type(() => PodStateResponse)
    pods: PodStateResponse[];

    @SpeakeasyMetadata()
    @Expose({ name: "replicas" })
    replicas: number;

    @SpeakeasyMetadata()
    @Expose({ name: "revision" })
    revision: number;

    @SpeakeasyMetadata()
    @Expose({ name: "status" })
    status: string;
}
