/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { MatchingCriteriaRequest } from "./matchingcriteriarequest";
import { ValuesSecretsRequest } from "./valuessecretsrequest";
import { Expose, Type } from "class-transformer";

/**
 * CreateResourceDefinitionRequest describes a new ResourceDefinition request.
 */
export class CreateResourceDefinitionRequestRequest extends SpeakeasyBase {
  /**
   * (Optional) The criteria to use when looking for a Resource Definition during the deployment.
   */
  @SpeakeasyMetadata({ elemType: MatchingCriteriaRequest })
  @Expose({ name: "criteria" })
  @Type(() => MatchingCriteriaRequest)
  criteria?: MatchingCriteriaRequest[];

  /**
   * (Optional) Security account required by the driver.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "driver_account" })
  driverAccount?: string;

  /**
   * ValuesSecrets stores data that should be passed around split by sensitivity.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "driver_inputs" })
  @Type(() => ValuesSecretsRequest)
  driverInputs?: ValuesSecretsRequest;

  /**
   * The driver to be used to create the resource.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "driver_type" })
  driverType: string;

  /**
   * The Resource Definition ID.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "id" })
  id: string;

  /**
   * The display name.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "name" })
  name: string;

  /**
   * The Resource Type.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "type" })
  type: string;
}
