/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { DeltaMetadataRequest } from "./deltametadatarequest";
import { ModuleDeltasRequest } from "./moduledeltasrequest";
import { UpdateActionRequest } from "./updateactionrequest";
import { Expose, Type } from "class-transformer";

/**
 * A Deployment Delta (or just "Delta") describes the changes that must be applied to one Deployment Set to generate another Deployment Set. Deployment Deltas are the only way to create new Deployment Sets.
 *
 * @remarks
 *
 * Deployment Deltas can be created fully formed or combined together via PATCHing. They can also be generated from the difference between two Deployment Sets.
 *
 * **Basic Structure**
 *
 * ```
 *  {
 *    "id": <ID of the Deployment Delta.>,
 *    "metadata": {
 *      <Properties such as who created the Delta, which Environment it is associated to and a Human-friendly name>
 *    }
 *    "modules" : {
 *      "add" : {
 *        <ID of Module to add to the Deployment Set> : {
 *          <An entire Modules object>
 *        }
 *      },
 *      "remove": [
 *        <An array of Module IDs that should be removed from the Deployment Set>
 *      ],
 *     "update": {
 *        <ID of Module already in the Set to be updated> : [
 *          <An array of JSON Patch (Search Results (RFC 6902) objects scoped to the module>
 *        ]
 *      }
 *    }
 *  }
 * ```
 */
export class DeltaRequest extends SpeakeasyBase {
  /**
   * Ignored, but can be provided.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "id" })
  id?: string;

  @SpeakeasyMetadata()
  @Expose({ name: "metadata" })
  @Type(() => DeltaMetadataRequest)
  metadata?: DeltaMetadataRequest;

  /**
   * ModuleDeltas groups the different operations together.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "modules" })
  @Type(() => ModuleDeltasRequest)
  modules?: ModuleDeltasRequest;

  @SpeakeasyMetadata({ elemType: UpdateActionRequest })
  @Expose({ name: "shared" })
  @Type(() => UpdateActionRequest)
  shared?: UpdateActionRequest[];
}
