/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export class EnvironmentBaseRequest extends SpeakeasyBase {
  /**
   * The ID the Environment is referenced as.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "id" })
  id: string;

  /**
   * The Human-friendly name for the Environment.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "name" })
  name: string;

  /**
   * The Environment Type. This is used for organizing and managing Environments.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "type" })
  type: string;
}
