/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * The ID, Name, Type, and Deployment the Environment will be derived from.
 *
 * @remarks
 *
 *
 */
export class EnvironmentDefinitionRequest extends SpeakeasyBase {
    /**
     * Defines the existing Deployment the new Environment will be based on.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "from_deploy_id" })
    fromDeployId: string;

    /**
     * The ID the Environment is referenced as.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id: string;

    /**
     * The Human-friendly name for the Environment.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name: string;

    /**
     * The Environment Type. This is used for organizing and managing Environments.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "type" })
    type: string;
}
