/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { DeploymentResponse } from "./deploymentresponse";
import { Expose, Type } from "class-transformer";

/**
 * Environments are independent spaces where Applications can run. An Application is always deployed into an Environment.
 */
export class EnvironmentResponse extends SpeakeasyBase {
  /**
   * The timestamp in UTC of when the Environment was created.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "created_at" })
  createdAt: string;

  /**
   * The user who created the Environment
   */
  @SpeakeasyMetadata()
  @Expose({ name: "created_by" })
  createdBy: string;

  /**
   * Deployments represent updates to the running state of an Environment.
   *
   * @remarks
   *
   * Deployments are made by applying _Deltas_ to a state defined by an existing Deployment. The Environment’s from_deploy property defines the Deployment. This Deployment is usually but not always in the current Environment. If the Deployment is from another Environment, the state of that Environment will be "cloned" into the current Environment with the option to apply a Delta.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "from_deploy" })
  @Type(() => DeploymentResponse)
  fromDeploy?: DeploymentResponse;

  /**
   * The ID the Environment is referenced as.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "id" })
  id: string;

  /**
   * Deployments represent updates to the running state of an Environment.
   *
   * @remarks
   *
   * Deployments are made by applying _Deltas_ to a state defined by an existing Deployment. The Environment’s from_deploy property defines the Deployment. This Deployment is usually but not always in the current Environment. If the Deployment is from another Environment, the state of that Environment will be "cloned" into the current Environment with the option to apply a Delta.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "last_deploy" })
  @Type(() => DeploymentResponse)
  lastDeploy?: DeploymentResponse;

  /**
   * The Human-friendly name for the Environment.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "name" })
  name: string;

  /**
   * The Environment Type. This is used for organizing and managing Environments.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "type" })
  type: string;
}
