/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * ErrorInfo is returned by a handler in case of an error.
 */
export class ErrorInfoResponse extends SpeakeasyBase {
  /**
   * An error details
   */
  @SpeakeasyMetadata()
  @Expose({ name: "error" })
  error: string;
}
