/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * Properties which identify an event .
 */
export class EventBaseResponse extends SpeakeasyBase {
  /**
   * Event scope
   */
  @SpeakeasyMetadata()
  @Expose({ name: "scope" })
  scope: string;

  /**
   * Event type
   */
  @SpeakeasyMetadata()
  @Expose({ name: "type" })
  type: string;
}
