/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * Events available for triggering automated jobs.
 */
export class EventResponse extends SpeakeasyBase {
    /**
     * List of event properties which can be used as variables for this event
     */
    @SpeakeasyMetadata()
    @Expose({ name: "properties" })
    properties: string[];

    /**
     * Event scope
     */
    @SpeakeasyMetadata()
    @Expose({ name: "scope" })
    scope: string;

    /**
     * Event type
     */
    @SpeakeasyMetadata()
    @Expose({ name: "type" })
    type: string;
}
