/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * HumanitecError represents a standard Humanitec Error
 */
export class HumanitecErrorResponse extends SpeakeasyBase {
  /**
   * (Optional) Additional information is enclosed here.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "details" })
  details?: Record<string, any>;

  /**
   * A short code to help with error identification.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "error" })
  error: string;

  /**
   * A Human readable message about the error.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "message" })
  message: string;
}
