/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * DEPRECATED: This type exists for historical compatibility and should not be used. Please use the [Artefact API](https://api-docs.humanitec.com/#tag/Artefact) instead.
 *
 * @remarks
 *
 * Holds the metadata associated withe a Container Image Build
 */
export class ImageBuildRequest extends SpeakeasyBase {
  /**
   * The branch name of the branch the build was built on
   */
  @SpeakeasyMetadata()
  @Expose({ name: "branch" })
  branch?: string;

  /**
   * The commit ID that this build was built from.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "commit" })
  commit?: string;

  /**
   * The fully qualified Image URL including registry, repository and tag.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "image" })
  image?: string;

  /**
   * The tag that the build was built from.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "tags" })
  tags?: string[];
}
