/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * MatchingCriteriaRule describes Matching Criteria rules.
 */
export class MatchingCriteriaRuleRequest extends SpeakeasyBase {
    /**
     * (Optional) The ID of the Application that the Resources should belong to.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "app_id" })
    appId?: string;

    /**
     * (Optional) The ID of the Environment that the Resources should belong to. If `env_type` is also set, it must match the Type of the Environment for the Criteria to match.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "env_id" })
    envId?: string;

    /**
     * (Optional) The Type of the Environment that the Resources should belong to. If `env_id` is also set, it must have an Environment Type that matches this parameter for the Criteria to match.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "env_type" })
    envType?: string;

    /**
     * (Optional) The ID of the Resource in the Deployment Set. The ID is normally a `.` separated path to the definition in the set, e.g. `modules.my-module.externals.my-database`.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "res_id" })
    resId?: string;
}
