/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * UpdateResourceAccountRequest describes the request to update the security account details.
 */
export class UpdateResourceAccountRequestRequest extends SpeakeasyBase {
    /**
     * Credentials associated with the account.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "credentials" })
    credentials?: Record<string, any>;

    /**
     * Display name.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name?: string;
}
