/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

/**
 * Source of the value, "app" for app level, "env" for app env level.
 */
export enum ValueSource {
  App = "app",
  Env = "env",
}
