/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * ValuesSecrets stores data that should be passed around split by sensitivity.
 */
export class ValuesSecretsRequest extends SpeakeasyBase {
    /**
     * Secrets section of the data set. Sensitive information is stored in the Vault and replaced with the Vault paths when sent outside.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "secrets" })
    secrets?: Record<string, any>;

    /**
     * Values section of the data set. Passed around as-is.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "values" })
    values?: Record<string, any>;
}
