/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * Definition of the new Shared Value.
 *
 * @remarks
 *
 *
 */
export class ValueCreatePayloadRequest extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "description" })
    description: string;

    @SpeakeasyMetadata()
    @Expose({ name: "is_secret" })
    isSecret?: boolean;

    @SpeakeasyMetadata()
    @Expose({ name: "key" })
    key: string;

    @SpeakeasyMetadata()
    @Expose({ name: "value" })
    value: string;
}
