/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export class ValueSetActionPayloadRequest extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "comment" })
    comment?: string;
}
