/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose, Transform } from "class-transformer";

/**
 * Workload Profiles provide the baseline configuration for Workloads in Applications in Humanitec. Developers can configure various features of a workload profile to suit their needs. Examples of features might be `schedules` used in Kubernetes CronJobs or `ingress` which might be used to expose Pods controlled by a Kubernetes Deployment.
 *
 * @remarks
 *
 * Workloads in Humanitec are implemented as Helm Charts which must implement a specific schema.
 */
export class WorkloadProfileResponse extends SpeakeasyBase {
  /**
   * Creation date
   */
  @SpeakeasyMetadata()
  @Expose({ name: "created_at" })
  @Transform(({ value }) => new Date(value), { toClassOnly: true })
  createdAt: Date;

  /**
   * User created the profile
   */
  @SpeakeasyMetadata()
  @Expose({ name: "created_by" })
  createdBy: string;

  /**
   * Workload Profile ID
   */
  @SpeakeasyMetadata()
  @Expose({ name: "id" })
  id: string;

  /**
   * The latest version of the profile
   */
  @SpeakeasyMetadata()
  @Expose({ name: "latest" })
  latest: string;

  /**
   * Organization ID
   */
  @SpeakeasyMetadata()
  @Expose({ name: "org_id" })
  orgId: string;
}
