/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";

export class GetOrgsOrgIdResourcesAccountTypesRequest extends SpeakeasyBase {
  /**
   * The Organization ID.
   *
   * @remarks
   *
   *
   */
  @SpeakeasyMetadata({
    data: "pathParam, style=simple;explode=false;name=orgId",
  })
  orgId: string;
}

export class GetOrgsOrgIdResourcesAccountTypesResponse extends SpeakeasyBase {
  /**
   * A possibly empty list of Resources Accounts Types.
   *
   * @remarks
   *
   *
   */
  @SpeakeasyMetadata({ elemType: shared.AccountTypeResponse })
  accountTypeResponses?: shared.AccountTypeResponse[];

  @SpeakeasyMetadata()
  contentType: string;

  /**
   * Internal application error.
   *
   * @remarks
   *
   *
   */
  @SpeakeasyMetadata()
  humanitecErrorResponse?: shared.HumanitecErrorResponse;

  @SpeakeasyMetadata()
  statusCode: number;

  @SpeakeasyMetadata()
  rawResponse?: AxiosResponse;
}
