/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";

export class GetOrgsOrgIdAppsAppIdValueSetVersionsValueSetVersionIdRequest extends SpeakeasyBase {
  /**
   * The Application ID.
   *
   * @remarks
   *
   *
   */
  @SpeakeasyMetadata({
    data: "pathParam, style=simple;explode=false;name=appId",
  })
  appId: string;

  /**
   * The Organization ID.
   *
   * @remarks
   *
   *
   */
  @SpeakeasyMetadata({
    data: "pathParam, style=simple;explode=false;name=orgId",
  })
  orgId: string;

  /**
   * The ValueSetVersion ID.
   *
   * @remarks
   *
   *
   */
  @SpeakeasyMetadata({
    data: "pathParam, style=simple;explode=false;name=valueSetVersionId",
  })
  valueSetVersionId: string;
}

export class GetOrgsOrgIdAppsAppIdValueSetVersionsValueSetVersionIdResponse extends SpeakeasyBase {
  @SpeakeasyMetadata()
  contentType: string;

  /**
   * ValueSetVersion with `valueSetVersionId` in App.
   *
   * @remarks
   *
   *
   */
  @SpeakeasyMetadata()
  humanitecErrorResponse?: shared.HumanitecErrorResponse;

  @SpeakeasyMetadata()
  statusCode: number;

  @SpeakeasyMetadata()
  rawResponse?: AxiosResponse;

  /**
   * The requested ValueSetVersion
   *
   * @remarks
   *
   *
   */
  @SpeakeasyMetadata()
  valueSetVersionResponse?: shared.ValueSetVersionResponse;
}
