/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";

export class GetOrgsOrgIdAppsAppIdDeltasRequest extends SpeakeasyBase {
  /**
   * The Application ID.
   *
   * @remarks
   *
   *
   */
  @SpeakeasyMetadata({
    data: "pathParam, style=simple;explode=false;name=appId",
  })
  appId: string;

  /**
   * If true, return archived Deltas.
   *
   * @remarks
   *
   *
   */
  @SpeakeasyMetadata({
    data: "queryParam, style=form;explode=true;name=archived",
  })
  archived?: boolean;

  /**
   * Only return Deltas associated with the specified Environment.
   *
   * @remarks
   *
   *
   */
  @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=env" })
  env?: string;

  /**
   * The Organization ID.
   *
   * @remarks
   *
   *
   */
  @SpeakeasyMetadata({
    data: "pathParam, style=simple;explode=false;name=orgId",
  })
  orgId: string;
}

export class GetOrgsOrgIdAppsAppIdDeltasResponse extends SpeakeasyBase {
  @SpeakeasyMetadata()
  contentType: string;

  /**
   * A possibly empty list of Deployment Deltas.
   *
   * @remarks
   *
   *
   */
  @SpeakeasyMetadata({ elemType: shared.DeltaResponse })
  deltaResponses?: shared.DeltaResponse[];

  @SpeakeasyMetadata()
  statusCode: number;

  @SpeakeasyMetadata()
  rawResponse?: AxiosResponse;
}
