/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";

export class GetOrgsOrgIdWorkloadProfilesProfileQidVersionsRequest extends SpeakeasyBase {
    /**
     * The Organization ID.
     *
     * @remarks
     *
     *
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=orgId" })
    orgId: string;

    /**
     * The Workload profile qualified ID.
     *
     * @remarks
     *
     *
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=profileQid" })
    profileQid: string;

    /**
     * Optional query parameter, defines version constraint pattern (https://github.com/Masterminds/semver#checking-version-constraints).
     *
     * @remarks
     *
     *
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=version" })
    version?: string;
}

export class GetOrgsOrgIdWorkloadProfilesProfileQidVersionsResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    contentType: string;

    /**
     * Workload Profile Versions not found or not accessible by the organization.
     *
     * @remarks
     *
     *
     */
    @SpeakeasyMetadata()
    humanitecErrorResponse?: shared.HumanitecErrorResponse;

    @SpeakeasyMetadata()
    statusCode: number;

    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;

    /**
     * A possibly empty list of Workload Profile Versions.
     *
     * @remarks
     *
     *
     */
    @SpeakeasyMetadata({ elemType: shared.WorkloadProfileVersionResponse })
    workloadProfileVersionResponses?: shared.WorkloadProfileVersionResponse[];
}
