/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";

export class GetOrgsOrgIdImagesImageIdBuildsRequest extends SpeakeasyBase {
  /**
   * The Image ID.
   *
   * @remarks
   *
   *
   */
  @SpeakeasyMetadata({
    data: "pathParam, style=simple;explode=false;name=imageId",
  })
  imageId: string;

  /**
   * The organization ID.
   *
   * @remarks
   *
   *
   */
  @SpeakeasyMetadata({
    data: "pathParam, style=simple;explode=false;name=orgId",
  })
  orgId: string;
}

export class GetOrgsOrgIdImagesImageIdBuildsResponse extends SpeakeasyBase {
  @SpeakeasyMetadata()
  contentType: string;

  /**
   * No Image with an ID of `imageId` found within the organization.
   *
   * @remarks
   *
   *
   */
  @SpeakeasyMetadata()
  humanitecErrorResponse?: shared.HumanitecErrorResponse;

  /**
   * Possibly empty list of Builds of Container Images.
   *
   * @remarks
   *
   *
   */
  @SpeakeasyMetadata({ elemType: shared.ImageBuildResponse })
  imageBuildResponses?: shared.ImageBuildResponse[];

  @SpeakeasyMetadata()
  statusCode: number;

  @SpeakeasyMetadata()
  rawResponse?: AxiosResponse;
}
