/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";

export class PostOrgsOrgIdWorkloadProfilesProfileQidVersionsRequestBodyFile extends SpeakeasyBase {
  @SpeakeasyMetadata({ data: "multipart_form, content=true" })
  content: Uint8Array;

  @SpeakeasyMetadata({ data: "multipart_form, name=file" })
  file: string;
}

/**
 * Workload profile version metadata.
 *
 * @remarks
 *
 *
 */
export class PostOrgsOrgIdWorkloadProfilesProfileQidVersionsRequestBody extends SpeakeasyBase {
  @SpeakeasyMetadata({ data: "multipart_form, file=true" })
  file?: PostOrgsOrgIdWorkloadProfilesProfileQidVersionsRequestBodyFile;

  /**
   * Each Workload Profile has one or more Versions associated with it. In order to add a version, a Workload Profile must first be created.
   */
  @SpeakeasyMetadata({ data: "multipart_form, name=metadata;json=true" })
  metadata?: shared.WorkloadProfileVersionRequest;
}

export class PostOrgsOrgIdWorkloadProfilesProfileQidVersionsRequest extends SpeakeasyBase {
  /**
   * Workload profile version metadata.
   *
   * @remarks
   *
   *
   */
  @SpeakeasyMetadata({ data: "request, media_type=multipart/form-data" })
  requestBody: PostOrgsOrgIdWorkloadProfilesProfileQidVersionsRequestBody;

  /**
   * The Organization ID.
   *
   * @remarks
   *
   *
   */
  @SpeakeasyMetadata({
    data: "pathParam, style=simple;explode=false;name=orgId",
  })
  orgId: string;

  /**
   * The Workload Profile ID.
   *
   * @remarks
   *
   *
   */
  @SpeakeasyMetadata({
    data: "pathParam, style=simple;explode=false;name=profileQid",
  })
  profileQid: string;
}

export class PostOrgsOrgIdWorkloadProfilesProfileQidVersionsResponse extends SpeakeasyBase {
  @SpeakeasyMetadata()
  contentType: string;

  /**
   * One or more request parameters is missing or invalid.
   *
   * @remarks
   *
   *
   */
  @SpeakeasyMetadata()
  humanitecErrorResponse?: shared.HumanitecErrorResponse;

  @SpeakeasyMetadata()
  statusCode: number;

  @SpeakeasyMetadata()
  rawResponse?: AxiosResponse;

  /**
   * The newly created Workload Profile Version metadata.
   *
   * @remarks
   *
   *
   */
  @SpeakeasyMetadata()
  workloadProfileVersionResponse?: shared.WorkloadProfileVersionResponse;
}
