/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { AxiosResponse } from "axios";

export class PutOrgsOrgIdAppsAppIdEnvsEnvIdRuntimePausedRequest extends SpeakeasyBase {
  /**
   * If the value is `true` the request is to pause an environment, if it is `false` is to resume an environment.
   *
   * @remarks
   *
   *
   */
  @SpeakeasyMetadata({ data: "request, media_type=application/json" })
  requestBody: boolean;

  /**
   * The Application ID.
   *
   * @remarks
   *
   *
   */
  @SpeakeasyMetadata({
    data: "pathParam, style=simple;explode=false;name=appId",
  })
  appId: string;

  /**
   * The Environment ID.
   *
   * @remarks
   *
   *
   */
  @SpeakeasyMetadata({
    data: "pathParam, style=simple;explode=false;name=envId",
  })
  envId: string;

  /**
   * The Organization ID.
   *
   * @remarks
   *
   *
   */
  @SpeakeasyMetadata({
    data: "pathParam, style=simple;explode=false;name=orgId",
  })
  orgId: string;
}

export class PutOrgsOrgIdAppsAppIdEnvsEnvIdRuntimePausedResponse extends SpeakeasyBase {
  @SpeakeasyMetadata()
  contentType: string;

  @SpeakeasyMetadata()
  statusCode: number;

  @SpeakeasyMetadata()
  rawResponse?: AxiosResponse;
}
